AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cloud Resume Challenge - Visitor Counter Backend (SAM IaC)

Globals:
  Function:
    Timeout: 10
    Runtime: python3.12

Resources:
  VisitorCountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CloudResumeCounter2026
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-counter"
      CodeUri: lambda/
      Handler: lambda_function.lambda_handler
      Description: Visitor count incrementer (SAM version)
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VisitorCountTable
      Environment:
        Variables:
          TABLE_NAME: !Ref VisitorCountTable
      Events:
        GetCount:
          Type: Api
          Properties:
            Path: /count
            Method: get

Outputs:
  ApiUrl:
    Description: "New API Gateway endpoint URL for visitor count"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/count"